[project]
name = "rocketdoo"
version = "2.2.0"
description = "Framework for creating Odoo development environments with Docker and custom templates."
authors = [
    { name = "Horacio MontaÃ±o", email = "horaciomontano@hdmsoft.com.ar" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.3",
    "copier>=9.2.0",
    "jinja2>=3.1.2",
    "pyyaml>=6.0",
    "rich>=13.0",
    "pyfiglet>=1.0",
    "questionary>=1.10.0"
]

[project.scripts]
rocketdoo = "rocketdoo.cli:main"
rkd = "rocketdoo.cli:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

# ğŸš€ Automatic package detection
[tool.setuptools.packages.find]
where = ["."]
include = ["rocketdoo*"]

# ğŸš€ Include templates in the package
[tool.setuptools.package-data]
rocketdoo = [
    "templates/**/*",
    "templates/**/**/*",
    "templates/**/.vscode/*",
    "templates/**/*.jinja",
    "templates/deploy/*",
    "templates/**/.*",
    "templates/**/**/.*",
]

[tool.setuptools]
include-package-data = true